const students = [
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },

  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },
  { name: "Cherino", height: 128, artworkSrc: "student-sprites/Cherino_00.png", artworkScaling: 1.13 },
  { name: "Kayoko", height: 157, artworkSrc: "student-sprites/Kayoko_00.png", artworkScaling: 1.1 },
  { name: "Tsukuyo", height: 180, artworkSrc: "student-sprites/Tsukuyo_00.png", artworkScaling: 1.07 },


];
