const students = [
  { name: "Cherino", height: 128, artSrc: "Cherino", artScale: 1.16, artOffset: 8 },
  { name: "Cherino", alt: "Hot Spring", height: 128, artSrc: "Cherino_(Hot_Spring)_diorama", artScale: 1.31, artOffset: 32, artShift: -8 },
  { name: "Ibuki", height: 128, artSrc: "Ibuki", artScale: 1.22, artOffset: 5 },
  { name: "Shun", alt: "Kid", height: 128, heightOverride: "???", artSrc: "Shun_(Kid)_diorama", artScale: 1.16, artOffset: 5, artShift: 20 },
  { name: "Momiji", height: 135, artSrc: "Momiji", artScale: 1.11, artOffset: 4 },
  { name: "Meru", height: 137, artSrc: "Meru", artScale: 1.16, artOffset: 5, artShift: 20 },
  { name: "Kokona", height: 139, artSrc: "Kokona", artScale: 1.12, artOffset: 3 },
  { name: "Hina", height: 142, artSrc: "Hina", artScale: 1.23, artOffset: 15, artShift: 12 },
  { name: "Hina", alt: "Dress", height: 142, artSrc: "Hina_(Dress)", artScale: 1.25, artOffset: 10 },
  { name: "Hina", alt: "Swimsuit", height: 142, artSrc: "Hina_(Swimsuit)_diorama", artScale: 1.24, artOffset: 20 },
  { name: "Kaede", height: 142, artSrc: "Kaede", artScale: 1.14, artOffset: 8, artShift: 12 },
  { name: "Kisaki", height: 142, artSrc: "Kisaki", artScale: 1.11, artOffset: 7 },
  { name: "Midori", height: 143, artSrc: "Midori", artScale: 1.11, artOffset: 5, artShift: 25 },
  { name: "Midori", alt: "Maid", height: 143, artSrc: "Midori_(Maid)", artScale: 1.12, artOffset: 5 },
  { name: "Momoi", height: 143, artSrc: "Momoi", artScale: 1.11, artOffset: 5, artShift: -30 },
  { name: "Momoi", alt: "Maid", height: 143, artSrc: "Momoi_(Maid)_diorama", artScale: 1.27, artOffset: 17 },
  { name: "Mutsuki", height: 144, artSrc: "Mutsuki", artScale: 1.18, artOffset: 5 },
  { name: "Mutsuki", alt: "New Year", height: 144, artSrc: "Mutsuki_(New_Year)", artScale: 1.14, artOffset: 7 },
  { name: "Hoshino", height: 145, artSrc: "Hoshino", artScale: 1.09, artOffset: 2 },
  { name: "Hoshino", alt: "Battle", height: 145, artSrc: "Hoshino_(Battle)", artScale: 1.1, artOffset: 5 },
  { name: "Hoshino", alt: "Swimsuit", height: 145, artSrc: "Hoshino_(Swimsuit)_diorama", artScale: 1.16, artOffset: 30 },
  { name: "Neru", height: 146, artSrc: "Neru", artScale: 1.16, artOffset: 10 },
  { name: "Neru", alt: "Bunny Girl", height: 146, artSrc: "Neru_(Bunny_Girl)", artScale: 1.1, artOffset: 5, artShift: -15 },
  { name: "Neru", alt: "School Uniform", height: 146, artSrc: "Neru_(School_Uniform)", artScale: 1.12, artOffset: 8 },
  { name: "Yoshimi", height: 146, artSrc: "Yoshimi", artScale: 1.16, artOffset: 0 },
  { name: "Yoshimi", alt: "Band", height: 146, artSrc: "Yoshimi_(Band)", artScale: 1.16, artOffset: 4 },
  { name: "Hikari", height: 147, artSrc: "Hikari", artScale: 1.14, artOffset: 7 },
  { name: "Nozomi", height: 147, artSrc: "Nozomi", artScale: 1.14, artOffset: 7 },
  { name: "Nodoka", height: 147, artSrc: "Nodoka", artScale: 1.11, artOffset: 5, artShift: 10 },
  { name: "Nodoka", alt: "Hot Spring", height: 147, artSrc: "Nodoka_(Hot_Spring)_diorama", artScale: 1.15, artOffset: 26, artShift: 10 },
  { name: "Fubuki", height: 148, artSrc: "Fubuki", artScale: 1.1, artOffset: 7, artShift: 10 },
  { name: "Fubuki", alt: "Swimsuit", height: 148, artSrc: "Fubuki_(Swimsuit)_diorama", artScale: 1.14, artOffset: 8, artShift: 15 },
  { name: "Kasumi", height: 148, artSrc: "Kasumi", artScale: 1.19, artOffset: 10, artShift: -25 },
  { name: "Koharu", height: 148, artSrc: "Koharu", artScale: 1.1, artOffset: 4 },
  { name: "Koharu", alt: "Swimsuit", height: 148, artSrc: "Koharu_(Swimsuit)", artScale: 1.09, artOffset: 4 },
  { name: "Azusa", height: 149, artSrc: "Azusa", artScale: 1.15, artOffset: 10, artShift: -20 },
  { name: "Azusa", alt: "Swimsuit", height: 149, artSrc: "Azusa_(Swimsuit)_diorama", artScale: 1.13, artOffset: 0 },
  { name: "Junko", height: 149, artSrc: "Junko", artScale: 1.11, artOffset: 7, artShift: 20 },
  { name: "Junko", alt: "New Year", height: 149, artSrc: "Junko_(New_Year)", artScale: 1.14, artOffset: 10, artShift: 10 },
  { name: "Koyuki", height: 149, artSrc: "Koyuki", artScale: 1.09, artOffset: 8, artShift: -40 },
  { name: "Maki", height: 149, artSrc: "Maki", artScale: 1.13, artOffset: 7, artShift: -40 },
  { name: "Maki", alt: "Camping", height: 149, artSrc: "Maki_(Camping)", artScale: 1.12, artOffset: 7 },
  { name: "Miyu", height: 149, artSrc: "Miyu_diorama", artScale: 1.11, artOffset: 10, artShift: 25 },
  { name: "Miyu", alt: "Swimsuit", height: 149, artSrc: "Miyu_(Swimsuit)", artScale: 1.124, artOffset: 14, artShift: -30 },
  { name: "Saya", height: 149, artSrc: "Saya", artScale: 1.13, artOffset: 6 },
  { name: "Saya", alt: "Casual", height: 149, artSrc: "Saya_(Casual)", artScale: 1.115, artOffset: 24, artShift: 25 },
  { name: "Seia", height: 149, artSrc: "Seia", artScale: 1.14, artOffset: 10, artShift: 16 },
  { name: "Hanae", height: 150, artSrc: "Hanae", artScale: 1.1, artOffset: 7, artShift: 20 },
  { name: "Hanae", alt: "Christmas", height: 150, artSrc: "Hanae_(Christmas)_diorama", artScale: 1.135, artOffset: 28, artShift: 5 },
  { name: "Yuzu", height: 150, artSrc: "Yuzu", artScale: 1.1, artOffset: 4, artShift: -20 },
  { name: "Yuzu", alt: "Maid", height: 150, artSrc: "Yuzu_(Maid)", artScale: 1.12, artOffset: 5 },
  { name: "Aoba", height: 151, artSrc: "Aoba", artScale: 1.13, artOffset: 4 },
  { name: "Iroha", height: 151, artSrc: "Iroha", artScale: 1.17, artOffset: 4 },
  { name: "Kotori", height: 151, artSrc: "Kotori", artScale: 1.08, artOffset: 2 },
  { name: "Kotori", alt: "Cheerleader", height: 151, artSrc: "Kotori_(Cheerleader)_diorama", artScale: 1.27, artOffset: 15 },
  { name: "Mari", height: 151, artSrc: "Mari", artScale: 1.12, artOffset: 6, artShift: -10 },
  { name: "Mari", alt: "Idol", height: 151, artSrc: "Mari_(Idol)", artScale: 1.13, artOffset: 9 },
  { name: "Mari", alt: "Sportswear", height: 151, artSrc: "Mari_(Sportswear)_diorama", artScale: 1.12, artOffset: 17 },
  { name: "Arisu", height: 152, artSrc: "Arisu", artScale: 1.07, artOffset: 3 },
  { name: "Arisu", alt: "Maid", height: 152, artSrc: "Arisu_(Maid)", artScale: 1.07, artOffset: 6, artShift: -16 },
  { name: "Natsu", height: 152, artSrc: "Natsu", artScale: 1.08, artOffset: 2 },
  { name: "Ayane", height: 153, artSrc: "Ayane", artScale: 1.07, artOffset: 5 },
  { name: "Ayane", alt: "Swimsuit", height: 153, artSrc: "Ayane_(Swimsuit)_diorama", artScale: 1.19, artOffset: 40 },
  { name: "Hare", height: 153, artSrc: "Hare", artScale: 1.1, artOffset: 7, artShift: -5 },
  { name: "Hare", alt: "Camping", height: 153, artSrc: "Hare_(Camping)", artScale: 1.07, artOffset: 2 },
  { name: "Michiru", height: 153, artSrc: "Michiru", artScale: 1.08, artOffset: 6 },
  { name: "Reisa", height: 153, artSrc: "Reisa", artScale: 1.065, artOffset: 2 },
  { name: "Serika", height: 153, artSrc: "Serika", artScale: 1.08, artOffset: 4 },
  { name: "Serika", alt: "New Year", height: 153, artSrc: "Serika_(New_Year)", artScale: 1.08, artOffset: 4 },
  { name: "Serika", alt: "Swimsuit", height: 153, artSrc: "Serika_(Swimsuit)", artScale: 1.11, artOffset: 16 },
  { name: "Shizuko", height: 153, artSrc: "Shizuko", artScale: 1.1, artOffset: 8 },
  { name: "Shizuko", alt: "Swimsuit", height: 153, artSrc: "Shizuko_(Swimsuit)_diorama", artScale: 1.17, artOffset: 14 },
  { name: "Hibiki", height: 154, artSrc: "Hibiki", artScale: 1, artOffset: 10, artShift: 20 },
  { name: "Hibiki", alt: "Cheerleader", height: 154, artSrc: "Hibiki_(Cheerleader)_diorama", artScale: 1.0645, artOffset: 15 },
  { name: "Hiyori", height: 155, artSrc: "Hiyori", artScale: 1.15, artOffset: 10, artShift: 20 },
  { name: "Hiyori", alt: "Swimsuit", height: 155, artSrc: "Hiyori_(Swimsuit)", artScale: 1.12, artOffset: 12 },
  { name: "Izuna", height: 155, artSrc: "Izuna", artScale: 1.1, artOffset: 6 },
  { name: "Izuna", alt: "Swimsuit", height: 155, artSrc: "Izuna_(Swimsuit)_diorama", artScale: 1.11, artOffset: 10 },
  { name: "Kazusa", height: 155, artSrc: "Kazusa", artScale: 1.1, artOffset: 8, artShift: -25 },
  { name: "Kazusa", alt: "Band", height: 155, artSrc: "Kazusa_(Band)", artScale: 1.14, artOffset: 12 },
  { name: "Mashiro", height: 155, artSrc: "Mashiro", artScale: 1.28, artOffset: 0, artShift: 8 },
  { name: "Mashiro", alt: "Swimsuit", height: 155, artSrc: "Mashiro_(Swimsuit)_diorama", artScale: 0.98, artOffset: 0, artShift: 10 },
  { name: "Sena", height: 155, artSrc: "Sena", artScale: 1.1, artOffset: 0 },
  { name: "Sena", alt: "Casual", height: 155, artSrc: "Sena_(Casual)_diorama", artScale: 1.11, artOffset: 14 },
  { name: "Yukari", height: 155, artSrc: "Yukari", artScale: 1.12, artOffset: 10, artShift: 30 },
  { name: "Mimori", height: 156, artSrc: "Mimori", artScale: 1.09, artOffset: 10 },
  { name: "Mimori", alt: "Swimsuit", height: 156, artSrc: "Mimori_(Swimsuit)_diorama", artScale: 1.02, artOffset: 60 },
  { name: "Miyako", height: 156, artSrc: "Miyako", artScale: 1.1, artOffset: 6 },
  { name: "Miyako", alt: "Swimsuit", height: 156, artSrc: "Miyako_(Swimsuit)", artScale: 1.11, artOffset: 10, artShift: -10 },
  { name: "Serina", height: 156, artSrc: "Serina", artScale: 1.1, artOffset: 0, artShift: 20 },
  { name: "Serina", alt: "Christmas", height: 156, artSrc: "Serina_(Christmas)_diorama", artScale: 1.13, artOffset: 18 },
  { name: "Shigure", height: 156, artSrc: "Shigure", artScale: 1.09, artOffset: 8 },
  { name: "Shigure", alt: "Hot Spring", height: 156, artSrc: "Shigure_(Hot_Spring)_diorama", artScale: 1.12, artOffset: 22 },
  { name: "Shiroko", height: 156, artSrc: "Shiroko", artScale: 1.1, artOffset: 7 },
  { name: "Shiroko", alt: "Riding", height: 156, artSrc: "Shiroko_(Riding)", artScale: 1.09, artOffset: 22, artShift: 12 },
  { name: "Shiroko", alt: "Swimsuit", height: 156, artSrc: "Shiroko_(Swimsuit)", artScale: 1.09, artOffset: 14 },
  { name: "Yuuka", height: 156, artSrc: "Yuuka", artScale: 1.075, artOffset: 3 },
  { name: "Yuuka", alt: "Pajama", height: 156, artSrc: "Yuuka_(Pajama)", artScale: 1.075, artOffset: 4, artShift: 10 },
  { name: "Yuuka", alt: "Sportswear", height: 156, artSrc: "Yuuka_(Sportswear)_diorama", artScale: 1.074, artOffset: 6 },
  { name: "Haruka", height: 157, artSrc: "Haruka", artScale: 1.09, artOffset: 4 },
  { name: "Haruka", alt: "New Year", height: 157, artSrc: "Haruka_(New_Year)", artScale: 1.08, artOffset: 10 },
  { name: "Iori", height: 157, artSrc: "Iori", artScale: 1.13, artOffset: 8, artShift: 20 },
  { name: "Iori", alt: "Swimsuit", height: 157, artSrc: "Iori_(Swimsuit)_diorama", artScale: 1.2, artOffset: 60 },
  { name: "Kayoko", height: 157, artSrc: "Kayoko", artScale: 1.117, artOffset: 5 },
  { name: "Kayoko", alt: "Dress", height: 157, artSrc: "Kayoko_(Dress)", artScale: 1.125, artOffset: 10 },
  { name: "Kayoko", alt: "New Year", height: 157, artSrc: "Kayoko_(New_Year)", artScale: 1.12, artOffset: 5 },
  { name: "Mika", height: 157, artSrc: "Mika", artScale: 1.17, artOffset: 7, artShift: -10 },
  { name: "Renge", height: 157, artSrc: "Renge", artScale: 1.16, artOffset: 6, artShift: -20 },
  { name: "Shimiko", height: 157, artSrc: "Shimiko", artScale: 1.07, artOffset: 6, artShift: 30 },
  { name: "Atsuko", height: 158, artSrc: "Atsuko", artScale: 1.14, artOffset: 8, artShift: 50 },
  { name: "Atsuko", alt: "Swimsuit", height: 158, artSrc: "Atsuko_(Swimsuit)", artScale: 1.138, artOffset: 8, artShift: 10 },
  { name: "Hatsune Miku", height: 158, artSrc: "Hatsune_Miku", artScale: 1.105, artOffset: 8 },
  { name: "Hifumi", height: 158, artSrc: "Hifumi", artScale: 1.08, artOffset: 12 },
  { name: "Hifumi", alt: "Swimsuit", height: 158, artSrc: "Hifumi_(Swimsuit)_diorama", artScale: 1.12, artOffset: 25 },
  { name: "Kotama", height: 158, artSrc: "Kotama", artScale: 1.121, artOffset: 7 },
  { name: "Kotama", alt: "Camping", height: 158, artSrc: "Kotama_(Camping)", artScale: 1.09, artOffset: 7 },
  { name: "Minori", height: 158, artSrc: "Minori", artScale: 1.1, artOffset: 6, artShift: -10 },
  { name: "Chinatsu", height: 159, artSrc: "Chinatsu", artScale: 1.1, artOffset: 0, artShift: -10 },
  { name: "Chinatsu", alt: "Hot Spring", height: 159, artSrc: "Chinatsu_(Hot_Spring)_diorama", artScale: 1.15, artOffset: 40, artShift: -40 },
  { name: "Chise", height: 159, artSrc: "Chise", artScale: 1.06, artOffset: 9, artShift: 30 },
  { name: "Chise", alt: "Swimsuit", height: 159, artSrc: "Chise_(Swimsuit)_diorama", artScale: 1.23, artOffset: 55 },
  { name: "Fuuka", height: 159, artSrc: "Fuuka", artScale: 1.13, artOffset: 12 },
  { name: "Fuuka", alt: "New Year", height: 159, artSrc: "Fuuka_(New_Year)_diorama", artScale: 1.22, artOffset: 30 },
  { name: "Kirara", height: 159, artSrc: "Kirara", artScale: 1.096, artOffset: 7 },
  { name: "Rei", height: 159, artSrc: "Rei", artScale: 1.14, artOffset: 7 },
  { name: "Airi", height: 160, artSrc: "Airi", artScale: 1.06, artOffset: 7 },
  { name: "Airi", alt: "Band", height: 160, artSrc: "Airi_(Band)", artScale: 1.093, artOffset: 2 },
  { name: "Aru", height: 160, artSrc: "Aru", artScale: 1.13, artOffset: 8, artShift: -15 },
  { name: "Aru", alt: "Dress", height: 160, artSrc: "Aru_(Dress)", artScale: 1.1, artOffset: 6 },
  { name: "Aru", alt: "New Year", height: 160, artSrc: "Aru_(New_Year)", artScale: 1.125, artOffset: 6, artShift: 15 },
  { name: "Chihiro", height: 160, artSrc: "Chihiro", artScale: 1.076, artOffset: 7, artShift: -20 },
  { name: "Kikyou", height: 160, artSrc: "Kikyou", artScale: 1.12, artOffset: 8, artShift: 15 },
  { name: "Nagisa", height: 160, artSrc: "Nagisa", artScale: 1, artOffset: 16, artShift: 8 },
  { name: "Nonomi", height: 160, artSrc: "Nonomi", artScale: 1.1, artOffset: 8, artShift: 25 },
  { name: "Nonomi", alt: "Swimsuit", height: 160, artSrc: "Nonomi_(Swimsuit)_diorama", artScale: 1.15, artOffset: 25, artShift: 10 },
  { name: "Sakurako", height: 160, artSrc: "Sakurako", artScale: 1.1, artOffset: 4 },
  { name: "Sakurako", alt: "Idol", height: 160, artSrc: "Sakurako_(Idol)", artScale: 1.092, artOffset: 4, artShift: 15 },
  { name: "Saten Ruiko", height: 160, artSrc: "Saten_Ruiko", artScale: 1.07, artOffset: 5 },
  { name: "Hanako", height: 161, artSrc: "Hanako", artScale: 1.09, artOffset: 2, artShift: 8 },
  { name: "Hanako", alt: "Swimsuit", height: 161, artSrc: "Hanako_(Swimsuit)", artScale: 1.092, artOffset: 2, artShift: 8 },
  { name: "Izumi", height: 161, artSrc: "Izumi", artScale: 1.094, artOffset: 4, artShift: 8 },
  { name: "Izumi", alt: "New Year", height: 161, artSrc: "Izumi_(New_Year)", artScale: 1.13, artOffset: 7, artShift: 8 },
  { name: "Izumi", alt: "Swimsuit", height: 161, artSrc: "Izumi_(Swimsuit)_diorama", artScale: 0.86, artOffset: 20, artShift: -22 },
  { name: "Kirino", height: 161, artSrc: "Kirino", artScale: 1.05, artOffset: 6, artShift: 12 },
  { name: "Kirino", alt: "Swimsuit", height: 161, artSrc: "Kirino_(Swimsuit)", artScale: 1.1, artOffset: 4, artShift: 20 },
  { name: "Misaka Mikoto", height: 161, artSrc: "Misaka_Mikoto", artScale: 1.068, artOffset: 6 },
  { name: "Nagusa", height: 161, artSrc: "Nagusa_diorama", artScale: 1.37, artOffset: 34, artShift: 10 },
  { name: "Noa", height: 161, artSrc: "Noa", artScale: 1.09, artOffset: 8, artShift: 10 },
  { name: "Noa", alt: "Pajama", height: 161, artSrc: "Noa_(Pajama)", artScale: 1.09, artOffset: 5 },
  { name: "Saki", height: 161, artSrc: "Saki", artScale: 1.107, artOffset: 6 },
  { name: "Saki", alt: "Swimsuit", height: 161, artSrc: "Saki_(Swimsuit)", artScale: 1.11, artOffset: 12, artShift: 5 },
  { name: "Wakamo", height: 161, artSrc: "Wakamo", artScale: 1.2, artOffset: 12, artShift: 15 },
  { name: "Wakamo", alt: "Swimsuit", height: 161, artSrc: "Wakamo_(Swimsuit)_diorama", artScale: 1.27, artOffset: 30 },
  { name: "Himari", height: 162, artSrc: "Himari", artScale: 0.9, artOffset: 0 },
  { name: "Suzumi", height: 162, artSrc: "Suzumi", artScale: 1.14, artOffset: 12, artShift: -20 },
  { name: "Tsubaki", height: 162, artSrc: "Tsubaki", artScale: 0.96, artOffset: 20,  artShift: 50 },
  { name: "Tsubaki", alt: "Guide", height: 162, artSrc: "Tsubaki_(Guide)", artScale: 1.13, artOffset: 10 },
  { name: "Tsurugi", height: 162, artSrc: "Tsurugi", artScale: 1.13, artOffset: 60 },
  { name: "Tsurugi", alt: "Swimsuit", height: 162, artSrc: "Tsurugi_(Swimsuit)_diorama", artScale: 1, artOffset: 50, artShift: 10 },
  { name: "Utaha", height: 162, artSrc: "Utaha", artScale: 1.09, artOffset: 10, artShift: 40 },
  { name: "Utaha", alt: "Cheerleader", height: 162, artSrc: "Utaha_(Cheerleader)_diorama", artScale: 1.18, artOffset: 14 },
  { name: "Haruna", height: 163, artSrc: "Haruna", artScale: 1.17, artOffset: 18 },
  { name: "Haruna", alt: "New Year", height: 163, artSrc: "Haruna_(New_Year)_diorama", artScale: 1.17, artOffset: 30 },
  { name: "Haruna", alt: "Sportswear", height: 163, artSrc: "Haruna_(Sportswear)_diorama", artScale: 1.13, artOffset: 30 },
  { name: "Ichika", height: 163, artSrc: "Ichika", artScale: 1.094, artOffset: 4, artShift: 17 },
  { name: "Misaki", height: 163, artSrc: "Misaki", artScale: 1.1, artOffset: 10, artShift: -34 },
  { name: "Moe", height: 163, artSrc: "Moe", artScale:0.91, artOffset: 10, artShift: 5 },
  { name: "Moe", alt: "Swimsuit", height: 163, artSrc: "Moe_(Swimsuit)", artScale: 1.086, artOffset: 7 },
  { name: "Akane", height: 164, artSrc: "Akane", artScale: 1.09, artOffset: 10 },
  { name: "Akane", alt: "Bunny Girl", height: 164, artSrc: "Akane_(Bunny_Girl)", artScale: 1.16, artOffset: 15 },
  { name: "Megu", height: 164, artSrc: "Megu", artScale: 1.12, artOffset: 10 },
  { name: "Ako", height: 165, artSrc: "Ako", artScale: 1.12, artOffset: 10, artShift: 5 },
  { name: "Ako", alt: "Dress", height: 165, artSrc: "Ako_(Dress)", artScale: 1.102, artOffset: 7 },
  { name: "Pina", height: 165, artSrc: "Pina", artScale: 1.12, artOffset: 8, artShift: -20 },
  { name: "Pina", alt: "Guide", height: 165, artSrc: "Pina_(Guide)", artScale: 1.11, artOffset: 9, artShift: 12 },
  { name: "Shiroko＊Terror", height: 165, artSrc: "Shiroko＊Terror", artScale: 1.11, artOffset: 12, artShift: -40 },
  { name: "Toki", height: 165, artSrc: "Toki", artScale: 1.1, artOffset: 15, artShift: 10 },
  { name: "Toki", alt: "Bunny Girl", height: 165, artSrc: "Toki_(Bunny_Girl)", artScale: 1.16, artOffset: 10 },
  { name: "Tomoe", height: 165, artSrc: "Tomoe", artScale: 1.162, artOffset: 10, artShift: -5 },
  { name: "Tomoe", alt: "Qipao", height: 165, artSrc: "Tomoe_(Qipao)", artScale: 1.11, artOffset: 9, artShift: -9 },
  { name: "Ui", height: 165, artSrc: "Ui", artScale: 1.105, artOffset: 10, artShift: 12 },
  { name: "Ui", alt: "Swimsuit", height: 165, artSrc: "Ui_(Swimsuit)_diorama", artScale: 1.17, artOffset: 28 },
  { name: "Umika", height: 165, artSrc: "Umika", artScale: 1.09, artOffset: 12, artShift: 5 },
  { name: "Hinata", height: 166, artSrc: "Hinata", artScale: 1.13, artOffset: 20, artShift: -7 },
  { name: "Hinata", alt: "Swimsuit", height: 166, artSrc: "Hinata_(Swimsuit)", artScale: 1.16, artOffset: 17, artShift: 7 },
  { name: "Kanna", height: 166, artSrc: "Kanna", artScale: 1.1, artOffset: 10 },
  { name: "Kanna", alt: "Swimsuit", height: 166, artSrc: "Kanna_(Swimsuit)", artScale: 1.108, artOffset: 10, artShift: -22 },
  { name: "Marina", height: 166, artSrc: "Marina", artScale: 1.075, artOffset: 13, artShift: 22 },
  { name: "Marina", alt: "Qipao", height: 166, artSrc: "Marina_(Qipao)", artScale: 1.09, artOffset: 10 },
  { name: "Mina", height: 166, artSrc: "Mina", artScale: 1.16, artOffset: 20 },
  { name: "Niya", height: 166, artSrc: "Niya", artScale: 1.12, artOffset: 12 },
  { name: "Akari", height: 167, artSrc: "Akari", artScale: 1.13, artOffset: 12, artShift: -7 },
  { name: "Akari", alt: "New Year", height: 167, artSrc: "Akari_(New_Year)_diorama", artScale: 1.22, artOffset: 45 },
  { name: "Asuna", height: 167, artSrc: "Asuna", artScale: 1.02, artOffset: 15 },
  { name: "Asuna", alt: "Bunny Girl", height: 167, artSrc: "Asuna_(Bunny_Girl)", artScale: 1.09, artOffset: 15 },
  { name: "Asuna", alt: "School Uniform", height: 167, artSrc: "Asuna_(School_Uniform)", artScale: 1.12, artOffset: 20 },
  { name: "Chiaki", height: 167, artSrc: "Chiaki", artScale: 1.175, artOffset: 10, artShift: -15 },
  { name: "Eimi", height: 167, artSrc: "Eimi", artScale: 1.1, artOffset: 14, artShift: -30 },
  { name: "Eimi", alt: "Swimsuit", height: 167, artSrc: "Eimi_(Swimsuit)_diorama", artScale: 1.12, artOffset: 35 },
  { name: "Saori", height: 167, artSrc: "Saori", artScale: 1.15, artOffset: 15, artShift: 10 },
  { name: "Saori", alt: "Dress", height: 167, artSrc: "Saori_(Dress)", artScale: 1.25, artOffset: 52, artShift: 20 },
  { name: "Saori", alt: "Swimsuit", height: 167, artSrc: "Saori_(Swimsuit)", artScale: 1.17, artOffset: 25 },
  { name: "Sumire", height: 167, artSrc: "Sumire", artScale: 1.15, artOffset: 20, artShift: 10 },
  { name: "Sumire", alt: "Part-Timer", height: 167, artSrc: "Sumire_(Part-Timer)", artScale: 1.1, artOffset: 10, artShift: -10 },
  { name: "Shokuhou Misaki", height: 167, heightOverride: "???", artSrc: "Shokuhou_Misaki", artScale: 1.1, artOffset: 10, artShift: -10 },
  { name: "Mine", height: 168, artSrc: "Mine", artScale: 1.15, artOffset: 20, artShift: -15 },
  { name: "Mine", alt: "Idol", height: 168, artSrc: "Mine_(Idol)", artScale: 1.12, artOffset: 15, artShift: 25 },
  { name: "Rumi", height: 168, artSrc: "Rumi", artScale: 1.17, artOffset: 25 },
  { name: "Makoto", height: 169, artSrc: "Makoto", artScale: 1.19, artOffset: 20, artShift: 8 },
  { name: "Reijo", height: 169, artSrc: "Reijo", artScale: 1.11, artOffset: 10, artShift: 10 },
  { name: "Juri", height: 170, artSrc: "Juri", artScale: 1.14, artOffset: 12, artShift: 5 },
  { name: "Juri", alt: "Part-Timer", height: 170, artSrc: "Juri_(Part-Timer)", artScale: 1.13, artOffset: 12, artShift: 10 },
  { name: "Karin", height: 170, artSrc: "Karin", artScale: 1.14, artOffset: 15, artShift: -32 },
  { name: "Karin", alt: "Bunny Girl", height: 170, artSrc: "Karin_(Bunny_Girl)", artScale: 1.15, artOffset: 10, artShift: 35 },
  { name: "Karin", alt: "School Uniform", height: 170, artSrc: "Karin_(School_Uniform)", artScale: 1.1, artOffset: 13, artShift: 55 },
  { name: "Rio", height: 171, artSrc: "Rio", artScale: 1.08, artOffset: 12, artShift: -10 },
  { name: "Satsuki", height: 172, artSrc: "Satsuki", artScale: 1.13, artOffset: 12 },
  { name: "Kaho", height: 173, artSrc: "Kaho", artScale: 1.13, artOffset: 20, artShift: 20 },
  { name: "Shun", height: 174, artSrc: "Shun", artScale: 1.2, artOffset: 30 },
  { name: "Hasumi", height: 179, artSrc: "Hasumi", artScale: 1.2, artOffset: 20 },
  { name: "Hasumi", alt: "Sportswear", height: 179, artSrc: "Hasumi_(Sportswear)", artScale: 1.2, artOffset: 35, artShift: -90 },
  { name: "Tsukuyo", height: 180, artSrc: "Tsukuyo", artScale: 1.05, artOffset: 10 },
];
