const students = [
  // { name: "Cherino", height: 128, artSrc: "Cherino_00.png", artScale: 1.1, artOffset: 03 },
  // { name: "Kayoko", height: 157, artSrc: "Kayoko_00.png", artScale: 1.1, artOffset: 0 },
  // { name: "Tsukuyo", height: 180, artSrc: "Tsukuyo_00.png", artScale: 1.07 },

  // { name: "Shokuhou Misaki", height: 0, artSrc: "Shokuhou_Misaki_00.png", artScale: 1.1, artOffset: 0 },
  // { name: "Shun (Kid)", height: 0, artSrc: "Shun_(Kid)_00.png", artScale: 1.1, artOffset: 0 },

  { name: "Cherino", height: 128, artSrc: "Cherino_00.png", artScale: 1.13, artOffset: 0 },
  { name: "Cherino", alt: "Hot Spring", height: 128, artSrc: "Cherino_(Hot_Spring)_diorama_00.png", artScale: 1.31, artOffset: 27 },
  { name: "Ibuki", height: 128, artSrc: "Ibuki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Momiji", height: 135, artSrc: "Momiji_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Meru", height: 137, artSrc: "Meru_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kokona", height: 139, artSrc: "Kokona_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hina", height: 142, artSrc: "Hina_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hina (Dress)", height: 142, artSrc: "Hina_(Dress)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hina (Swimsuit)", height: 142, artSrc: "Hina_(Swimsuit)_diorama_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kaede", height: 142, artSrc: "Kaede_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kisaki", height: 142, artSrc: "Kisaki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Midori", height: 143, artSrc: "Midori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Midori (Maid)", height: 143, artSrc: "Midori_(Maid)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Momoi", height: 143, artSrc: "Momoi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Momoi (Maid)", height: 143, artSrc: "Momoi_(Maid)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mutsuki", height: 144, artSrc: "Mutsuki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mutsuki (New Year)", height: 144, artSrc: "Mutsuki_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hoshino", height: 145, artSrc: "Hoshino_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hoshino (Battle)", height: 145, artSrc: "Hoshino_(Battle)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hoshino (Swimsuit)", height: 145, artSrc: "Hoshino_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Neru", height: 146, artSrc: "Neru_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Neru (Bunny Girl)", height: 146, artSrc: "Neru_(Bunny_Girl)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Neru (School Uniform)", height: 146, artSrc: "Neru_(School_Uniform)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yoshimi", height: 146, artSrc: "Yoshimi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yoshimi (Band)", height: 146, artSrc: "Yoshimi_(Band)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hikari", height: 147, artSrc: "Hikari_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nodoka", height: 147, artSrc: "Nodoka_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nodoka (Hot Spring)", height: 147, artSrc: "Nodoka_(Hot_Spring)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nozomi", height: 147, artSrc: "Nozomi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Fubuki", height: 148, artSrc: "Fubuki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Fubuki (Swimsuit)", height: 148, artSrc: "Fubuki_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kasumi", height: 148, artSrc: "Kasumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Koharu", height: 148, artSrc: "Koharu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Koharu (Swimsuit)", height: 148, artSrc: "Koharu_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Azusa", height: 149, artSrc: "Azusa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Azusa (Swimsuit)", height: 149, artSrc: "Azusa_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Junko", height: 149, artSrc: "Junko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Junko (New Year)", height: 149, artSrc: "Junko_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Koyuki", height: 149, artSrc: "Koyuki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Maki", height: 149, artSrc: "Maki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Maki (Camping)", height: 149, artSrc: "Maki_(Camping)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Miyu", height: 149, artSrc: "Miyu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Miyu (Swimsuit)", height: 149, artSrc: "Miyu_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saya", height: 149, artSrc: "Saya_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saya (Casual)", height: 149, artSrc: "Saya_(Casual)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Seia", height: 149, artSrc: "Seia_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hanae", height: 150, artSrc: "Hanae_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hanae (Christmas)", height: 150, artSrc: "Hanae_(Christmas)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yuzu", height: 150, artSrc: "Yuzu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yuzu (Maid)", height: 150, artSrc: "Yuzu_(Maid)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Aoba", height: 151, artSrc: "Aoba_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Iroha", height: 151, artSrc: "Iroha_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kotori", height: 151, artSrc: "Kotori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kotori (Cheerleader)", height: 151, artSrc: "Kotori_(Cheerleader)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mari", height: 151, artSrc: "Mari_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mari (Idol)", height: 151, artSrc: "Mari_(Idol)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mari (Sportswear)", height: 151, artSrc: "Mari_(Sportswear)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Arisu", height: 152, artSrc: "Arisu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Arisu (Maid)", height: 152, artSrc: "Arisu_(Maid)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Natsu", height: 152, artSrc: "Natsu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ayane", height: 153, artSrc: "Ayane_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ayane (Swimsuit)", height: 153, artSrc: "Ayane_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hare", height: 153, artSrc: "Hare_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hare (Camping)", height: 153, artSrc: "Hare_(Camping)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Michiru", height: 153, artSrc: "Michiru_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Reisa", height: 153, artSrc: "Reisa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Serika", height: 153, artSrc: "Serika_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Serika (New Year)", height: 153, artSrc: "Serika_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Serika (Swimsuit)", height: 153, artSrc: "Serika_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shizuko", height: 153, artSrc: "Shizuko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shizuko (Swimsuit)", height: 153, artSrc: "Shizuko_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hibiki", height: 154, artSrc: "Hibiki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hibiki (Cheerleader)", height: 154, artSrc: "Hibiki_(Cheerleader)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hiyori", height: 155, artSrc: "Hiyori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hiyori (Swimsuit)", height: 155, artSrc: "Hiyori_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Izuna", height: 155, artSrc: "Izuna_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Izuna (Swimsuit)", height: 155, artSrc: "Izuna_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kazusa", height: 155, artSrc: "Kazusa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kazusa (Band)", height: 155, artSrc: "Kazusa_(Band)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mashiro", height: 155, artSrc: "Mashiro_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mashiro (Swimsuit)", height: 155, artSrc: "Mashiro_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sena", height: 155, artSrc: "Sena_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sena (Casual)", height: 155, artSrc: "Sena_(Casual)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yukari", height: 155, artSrc: "Yukari_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mimori", height: 156, artSrc: "Mimori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mimori (Swimsuit)", height: 156, artSrc: "Mimori_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Miyako", height: 156, artSrc: "Miyako_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Miyako (Swimsuit)", height: 156, artSrc: "Miyako_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Serina", height: 156, artSrc: "Serina_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Serina (Christmas)", height: 156, artSrc: "Serina_(Christmas)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shigure", height: 156, artSrc: "Shigure_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shigure (Hot Spring)", height: 156, artSrc: "Shigure_(Hot_Spring)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shiroko", height: 156, artSrc: "Shiroko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shiroko (Riding)", height: 156, artSrc: "Shiroko_(Riding)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shiroko (Swimsuit)", height: 156, artSrc: "Shiroko_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yuuka", height: 156, artSrc: "Yuuka_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yuuka (Pajama)", height: 156, artSrc: "Yuuka_(Pajama)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Yuuka (Sportswear)", height: 156, artSrc: "Yuuka_(Sportswear)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Haruka", height: 157, artSrc: "Haruka_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Haruka (New Year)", height: 157, artSrc: "Haruka_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Iori", height: 157, artSrc: "Iori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Iori (Swimsuit)", height: 157, artSrc: "Iori_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kayoko", height: 157, artSrc: "Kayoko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kayoko (Dress)", height: 157, artSrc: "Kayoko_(Dress)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kayoko (New Year)", height: 157, artSrc: "Kayoko_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mika", height: 157, artSrc: "Mika_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Renge", height: 157, artSrc: "Renge_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shimiko", height: 157, artSrc: "Shimiko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Atsuko", height: 158, artSrc: "Atsuko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Atsuko (Swimsuit)", height: 158, artSrc: "Atsuko_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hatsune Miku", height: 158, artSrc: "Hatsune_Miku_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hifumi", height: 158, artSrc: "Hifumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hifumi (Swimsuit)", height: 158, artSrc: "Hifumi_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kotama", height: 158, artSrc: "Kotama_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kotama (Camping)", height: 158, artSrc: "Kotama_(Camping)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Minori", height: 158, artSrc: "Minori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chinatsu", height: 159, artSrc: "Chinatsu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chinatsu (Hot Spring)", height: 159, artSrc: "Chinatsu_(Hot_Spring)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chise", height: 159, artSrc: "Chise_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chise (Swimsuit)", height: 159, artSrc: "Chise_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Fuuka", height: 159, artSrc: "Fuuka_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Fuuka (New Year)", height: 159, artSrc: "Fuuka_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kirara", height: 159, artSrc: "Kirara_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Rei", height: 159, artSrc: "Rei_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Airi", height: 160, artSrc: "Airi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Airi (Band)", height: 160, artSrc: "Airi_(Band)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Aru", height: 160, artSrc: "Aru_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Aru (Dress)", height: 160, artSrc: "Aru_(Dress)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Aru (New Year)", height: 160, artSrc: "Aru_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chihiro", height: 160, artSrc: "Chihiro_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kikyou", height: 160, artSrc: "Kikyou_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nagisa", height: 160, artSrc: "Nagisa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nonomi", height: 160, artSrc: "Nonomi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nonomi (Swimsuit)", height: 160, artSrc: "Nonomi_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sakurako", height: 160, artSrc: "Sakurako_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sakurako (Idol)", height: 160, artSrc: "Sakurako_(Idol)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saten Ruiko", height: 160, artSrc: "Saten_Ruiko_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hanako", height: 161, artSrc: "Hanako_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hanako (Swimsuit)", height: 161, artSrc: "Hanako_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Izumi", height: 161, artSrc: "Izumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Izumi (New Year)", height: 161, artSrc: "Izumi_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Izumi (Swimsuit)", height: 161, artSrc: "Izumi_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kirino", height: 161, artSrc: "Kirino_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kirino (Swimsuit)", height: 161, artSrc: "Kirino_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Misaka Mikoto", height: 161, artSrc: "Misaka_Mikoto_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Nagusa", height: 161, artSrc: "Nagusa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Noa", height: 161, artSrc: "Noa_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Noa (Pajama)", height: 161, artSrc: "Noa_(Pajama)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saki", height: 161, artSrc: "Saki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saki (Swimsuit)", height: 161, artSrc: "Saki_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Wakamo", height: 161, artSrc: "Wakamo_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Wakamo (Swimsuit)", height: 161, artSrc: "Wakamo_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Himari", height: 162, artSrc: "Himari_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Suzumi", height: 162, artSrc: "Suzumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tsubaki", height: 162, artSrc: "Tsubaki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tsubaki (Guide)", height: 162, artSrc: "Tsubaki_(Guide)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tsurugi", height: 162, artSrc: "Tsurugi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tsurugi (Swimsuit)", height: 162, artSrc: "Tsurugi_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Utaha", height: 162, artSrc: "Utaha_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Utaha (Cheerleader)", height: 162, artSrc: "Utaha_(Cheerleader)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Haruna", height: 163, artSrc: "Haruna_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Haruna (New Year)", height: 163, artSrc: "Haruna_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Haruna (Sportswear)", height: 163, artSrc: "Haruna_(Sportswear)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ichika", height: 163, artSrc: "Ichika_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Misaki", height: 163, artSrc: "Misaki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Moe", height: 163, artSrc: "Moe_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Moe (Swimsuit)", height: 163, artSrc: "Moe_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Akane", height: 164, artSrc: "Akane_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Akane (Bunny Girl)", height: 164, artSrc: "Akane_(Bunny_Girl)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Megu", height: 164, artSrc: "Megu_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ako", height: 165, artSrc: "Ako_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ako (Dress)", height: 165, artSrc: "Ako_(Dress)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Pina", height: 165, artSrc: "Pina_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Pina (Guide)", height: 165, artSrc: "Pina_(Guide)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shiroko＊Terror", height: 165, artSrc: "Shiroko＊Terror_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Toki", height: 165, artSrc: "Toki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Toki (Bunny Girl)", height: 165, artSrc: "Toki_(Bunny_Girl)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tomoe", height: 165, artSrc: "Tomoe_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tomoe (Qipao)", height: 165, artSrc: "Tomoe_(Qipao)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ui", height: 165, artSrc: "Ui_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Ui (Swimsuit)", height: 165, artSrc: "Ui_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Umika", height: 165, artSrc: "Umika_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hinata", height: 166, artSrc: "Hinata_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hinata (Swimsuit)", height: 166, artSrc: "Hinata_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kanna", height: 166, artSrc: "Kanna_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kanna (Swimsuit)", height: 166, artSrc: "Kanna_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Marina", height: 166, artSrc: "Marina_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Marina (Qipao)", height: 166, artSrc: "Marina_(Qipao)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mina", height: 166, artSrc: "Mina_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Niya", height: 166, artSrc: "Niya_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Akari", height: 167, artSrc: "Akari_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Akari (New Year)", height: 167, artSrc: "Akari_(New_Year)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Asuna", height: 167, artSrc: "Asuna_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Asuna (Bunny Girl)", height: 167, artSrc: "Asuna_(Bunny_Girl)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Asuna (School Uniform)", height: 167, artSrc: "Asuna_(School_Uniform)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Chiaki", height: 167, artSrc: "Chiaki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Eimi", height: 167, artSrc: "Eimi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Eimi (Swimsuit)", height: 167, artSrc: "Eimi_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saori", height: 167, artSrc: "Saori_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saori (Dress)", height: 167, artSrc: "Saori_(Dress)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Saori (Swimsuit)", height: 167, artSrc: "Saori_(Swimsuit)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sumire", height: 167, artSrc: "Sumire_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Sumire (Part-Timer)", height: 167, artSrc: "Sumire_(Part-Timer)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mine", height: 168, artSrc: "Mine_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Mine (Idol)", height: 168, artSrc: "Mine_(Idol)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Rumi", height: 168, artSrc: "Rumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Makoto", height: 169, artSrc: "Makoto_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Reijo", height: 169, artSrc: "Reijo_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Juri", height: 170, artSrc: "Juri_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Juri (Part-Timer)", height: 170, artSrc: "Juri_(Part-Timer)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Karin", height: 170, artSrc: "Karin_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Karin (Bunny Girl)", height: 170, artSrc: "Karin_(Bunny_Girl)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Karin (School Uniform)", height: 170, artSrc: "Karin_(School_Uniform)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Rio", height: 171, artSrc: "Rio_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Satsuki", height: 172, artSrc: "Satsuki_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Kaho", height: 173, artSrc: "Kaho_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Shun", height: 174, artSrc: "Shun_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hasumi", height: 179, artSrc: "Hasumi_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Hasumi (Sportswear)", height: 179, artSrc: "Hasumi_(Sportswear)_00.png", artScale: 1.1, artOffset: 0 },
  { name: "Tsukuyo", height: 180, artSrc: "Tsukuyo_00.png", artScale: 1.07, artOffset: 0 },
];
